ANTICOMBATPLACE: false
KITMAP: false
TAB: true
SPAWNBUFFER: 300
WARZONERADIUS: 1000
STARTING_BALANCE: 1500
MAPNUM: 1
BOARDTITLE: "&5&lFishyPVP &7\u2758 &fKitmap"
TITLE: "Kitmap"

DEATHBAN:
  Bronze:
    PERMISSION: "deathban.bronze"
    TIME: 50m
  Silver:
    PERMISSION: "deathban.siver"
    TIME: 30m
  Gold:
    PERMISSION: "deathban.gold"
    TIME: 20m
  Legend:
    PERMISSION: "deathban.legend"
    TIME: 5m
  Desire:
    PERMISSION: "deathban.desire"
    TIME: 2m
  Youtuber:
    PERMISSION: "deathban.youtuber"
    TIME: 1m
  Famous:
    PERMISSION: "deathban.famous"
    TIME: 1m
  Partner:
    PERMISSION: "deathban.partner"
    TIME: 1m
  Bronze:
    PERMISSION: "deathban.gold"
    TIME: 1m
  default:
    PERMISSION: "deathban.default"
    TIME: 60m
EVENT:
  KOTH_COMMAND: "broadcast koth %PLAYER%"
  CONQUEST_COMMAND: "broadcast test %PLAYER%"
  KILL_THE_KING_COMMANDS:
    - "broadcast %player% won"
ALLY_COLOR: "AQUA"
WARZONE_COLOR: "DARK_RED"
WILDERNESS_COLOR: "DARK_GREEN"
SAFEZONE_COLOR: "GREEN"
ROAD_COLOR: "YELLOW"
ENEMY_COLOR: "RED"
TEAMMATE_COLOR: "GREEN"
ARCHER_COLOR: "YELLOW"
ENCHANTMENT_LIMIT:
  DAMAGE_ALL: 1
  PROTECTION_ENVIRONMENTAL: 1
  ARROW_KNOCKBACK: 1
  KNOCKBACK: 0
  FIRE_ASPECT: 0
  THORNS: 0
  SILK_TOUCH: 1
  PROTECTION_FIRE: 3
  LURE: 3
  LUCK: 3
  LOOT_BONUS_MOBS: 3
  OXYGEN: 3
  WATER_WORKER: 1
  LOOT_BONUS_BLOCKS: 3
  PROTECTION_PROJECTILE: 3
  PROTECTION_EXPLOSIONS: 3
  ARROW_FIRE: 0
  DURABILITY: 3
  ARROW_DAMAGE: 4
POTION_LIMIT:
  INSTANT_DAMAGE: 0
  REGEN: 0
  STRENGTH: 0
  WEAKNESS: 0
  SLOWNESS: 0
  INVISIBILITY: 1
  POISON: 1
  INSTANT_HEAL: 2
  NIGHT_VISION: 1
  WATER_BREATHING: 0
  WATER: 0
  FIRE_RESISTANCE: 1
  SPEED: 2
BORDERS:
  NORMAL: 2500
  THE_END: 1500
  NETHER: 2500
FACTION:
  MAXPLAYERS: 5
  MAXALLIES: 0
  MINDTR: -5
  MAXDTR: 6
  MINIMUMNAMECHARACTERS: 3
  MAXNAMECHARACTERS: 16
  MAXCLAIMS: 3
  MAXHEIGHT: -1
  HOMETIME:
    OVERWORLD: 10
    END: 10
    NETHER: 10